version: '3'
services:
  # MongoDB
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodata:/data/db
    restart: always
  # Mongo Express Web-based MongoDB admin interface
  mongo-express:
    image: mongo-express
    depends_on:
      - 'mongo'
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    volumes:
      - ./mongodata
    restart: always